server:
  port: 8888
spring:
  application:
    name: config-service
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Laura-2950/spring-cloud-config/
          searchPaths: movie-catalog-II
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Config Microservice